In [1]:
import pandas as pd
import numpy as np

In [2]:
dtype = {'case_id' : str}
collisions = pd.read_csv('data/old/collisions.csv', dtype=dtype)
parties = pd.read_csv('data/old/parties.csv', dtype=dtype)
victims = pd.read_csv('data/old/victims.csv', dtype=dtype)
road_states = pd.read_csv('data/old/road_state.csv', dtype=dtype)

C:\Users\steph\miniconda3\envs\myenv\lib\site-packages\IPython\core\interactiveshell.py:3166: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\steph\miniconda3\envs\myenv\lib\site-packages\IPython\core\interactiveshell.py:3166: DtypeWarning: Columns (13) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


# Checking columns

In [3]:
parties.columns

Index(['id', 'case_id', 'party_number', 'at_fault', 'party_sex', 'party_type',
       'party_age', 'party_sobriety', 'party_drug_physical',
       'movement_preceding_collision', 'hazardous_materials', 'cellphone_use',
       'financial_responsibility', 'school_bus_related', 'vehicle_id', 'afid',
       'seid'],
      dtype='object')

In [4]:
collisions.columns

Index(['case_id', 'collision_date', 'collision_time', 'collision_severity',
       'type_of_collision', 'officer_id', 'process_date', 'ramp_intersection',
       'tow_away', 'hit_and_run', 'location_id', 'pcf_id', 'road_state_id',
       'weather_id_1', 'weather_id_2'],
      dtype='object')

In [5]:
victims.columns

Index(['id', 'case_id', 'party_number', 'victim_age', 'victim_sex',
       'victim_role', 'victim_degree_of_injury', 'victim_ejected',
       'victim_seating_position', 'seid'],
      dtype='object')

In [6]:
road_states.columns

Index(['road_state_id', 'road_condition_1', 'road_condition_2', 'road_surface',
       'lighting'],
      dtype='object')

# Removing road_states outliers

In [7]:
print(road_states.road_surface.unique())
def remove_H(x):
    if (x == 'H'):
        return None
    else: 
        return x

road_states['road_surface'] = road_states['road_surface'].map(remove_H, na_action='ignore')

['dry' 'wet' 'snowy' nan 'slippery' 'H']


In [8]:
print(road_states.road_surface.unique())
road_states

['dry' 'wet' 'snowy' nan 'slippery' None]


road_state_id road_condition_1 road_condition_2 road_surface  \
0                0           normal              NaN          dry   
1                1           normal              NaN          dry   
2                2           normal              NaN          dry   
3                3           normal              NaN          dry   
4                4           normal              NaN          dry   
..             ...              ...              ...          ...   
685            685              NaN   loose material          wet   
686            686            other            holes          dry   
687            687              NaN           normal          wet   
688            688      obstruction     construction     slippery   
689            689    reduced width     construction          dry   

                       lighting  
0                      daylight  
1                           NaN  
2                  dusk or dawn  
3       dark with street lights  
4    dark with no street lights  
..                          ...  
685  dark with no street lights  
686                    daylight  
687  dark with no street lights  
688                    daylight  
689                    daylight  

[690 rows x 5 columns]

In [9]:
road_states.to_csv("data/new/road_states.csv")

In [10]:
road_states_new = pd.read_csv('data/new/road_states.csv', dtype=dtype)
road_states_new.road_surface.unique()

array(['dry', 'wet', 'snowy', nan, 'slippery'], dtype=object)

# Remove Collisions outliers

In [11]:
def hit_and_run_D_outlier(x):
    if (x == 'D'):
        return None
    else:
        return x

print(collisions.hit_and_run.unique())

collisions['hit_and_run'] = collisions['hit_and_run'].map(hit_and_run_D_outlier, na_action='ignore')

['not hit and run' 'misdemeanor' 'felony' 'D']


In [12]:
print(collisions.hit_and_run.unique())


['not hit and run' 'misdemeanor' 'felony' None]


In [13]:
collisions.to_csv("data/new/collisions.csv")

In [14]:
collisions_new = pd.read_csv('data/new/collisions.csv', dtype=dtype)
collisions_new.hit_and_run.unique()

C:\Users\steph\miniconda3\envs\myenv\lib\site-packages\IPython\core\interactiveshell.py:3166: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


array(['not hit and run', 'misdemeanor', 'felony', nan], dtype=object)

# Remove Parties outliers and map party_sex

In [15]:
def cellphone_use_map_integers(x):
    if (x == '1'):
        return 'B'
    if (x == '2'):
        return 'C'
    if (x == '3'):
        return 'D'
    else:
        return x

def map_sex(x):
    if (x == 'male'):
        return 'M'
    elif (x == 'female'):
        return 'F'
    else:
        return x

def party_drug_physical_remove_G(x):
    if (x == 'G'):
        return None
    else:
        return x

print(parties.party_drug_physical.unique())
print(parties.cellphone_use.unique())
print(parties.party_sex.unique())
print(parties.columns)

[nan 'H' 'G' 'E' 'I' 'F']
['C' 'D' nan 'B' '3' '2' '1']
['female' nan 'male']
Index(['id', 'case_id', 'party_number', 'at_fault', 'party_sex', 'party_type',
       'party_age', 'party_sobriety', 'party_drug_physical',
       'movement_preceding_collision', 'hazardous_materials', 'cellphone_use',
       'financial_responsibility', 'school_bus_related', 'vehicle_id', 'afid',
       'seid'],
      dtype='object')


In [16]:
parties['party_drug_physical'] = parties['party_drug_physical'].map(party_drug_physical_remove_G, na_action='ignore')
parties['cellphone_use'] = parties['cellphone_use'].map(cellphone_use_map_integers, na_action='ignore')
parties['party_sex'] = parties['party_sex'].map(
    map_sex, na_action='ignore'
)

print(parties.party_drug_physical.unique())
print(parties.cellphone_use.unique())
print(parties.party_sex.unique())

[nan 'H' None 'E' 'I' 'F']
['C' 'D' nan 'B']
['F' nan 'M']


In [17]:
#parties.to_csv("data/new/parties.csv")

# Remove Victims outliers and map victim_sex

In [18]:
def victim_degree_of_injury_replace_7(x):
    if (x == '7'):
        return 'possible injury'
    else:
        return x

def victim_ejected_remove_4(x):
    if (x == 4):
        return None
    else:
        return x 

print(victims.victim_degree_of_injury.unique())
print(victims.victim_ejected.unique())
print(victims.victim_sex.unique())

['no injury' 'severe injury' 'complaint of pain' 'other visible injury'
 'killed' '7']
[ 0.  1.  3. nan  2.  4.]
['male' 'female' nan]


In [19]:
victims['victim_degree_of_injury'] = victims['victim_degree_of_injury'].map(victim_degree_of_injury_replace_7, na_action='ignore')
victims['victim_ejected'] = victims['victim_ejected'].map(victim_ejected_remove_4, na_action='ignore')
victims['victim_sex'] = victims['victim_sex'].map(map_sex, na_action='ignore')

print(victims.victim_degree_of_injury.unique())
print(victims.victim_ejected.unique())
print(victims.victim_sex.unique())

['no injury' 'severe injury' 'complaint of pain' 'other visible injury'
 'killed' 'possible injury']
[ 0.  1.  3. nan  2.]
['M' 'F' nan]


In [20]:
victims.to_csv("data/new/victims.csv")

In [21]:
victims_new = pd.read_csv('data/new/victims.csv', dtype=dtype)
print(victims.victim_degree_of_injury.unique())
print(victims.victim_ejected.unique())
print(victims.victim_sex.unique())

['no injury' 'severe injury' 'complaint of pain' 'other visible injury'
 'killed' 'possible injury']
[ 0.  1.  3. nan  2.]
['M' 'F' nan]


# Convert boolean values to numbers

In [22]:
def convert_hazardous_to_number(x):
    if (x == 'A'):
        return 1
    else:
        return 0

parties.hazardous_materials.unique()

array([nan, 'A'], dtype=object)

In [23]:
parties['hazardous_materials'] = parties['hazardous_materials'].map(convert_hazardous_to_number)

parties.hazardous_materials.unique()

array([0, 1], dtype=int64)

In [24]:
def convert_school_bus_related_to_number(x):
    if (x == 'E'):
        return 1
    else:
        return 0

parties.school_bus_related.unique()

array([nan, 'E'], dtype=object)

In [25]:
parties['school_bus_related'] = parties['school_bus_related'].map(convert_school_bus_related_to_number)

parties.school_bus_related.unique()

array([0, 1], dtype=int64)

In [26]:
parties.to_csv("data/new/parties.csv")

In [27]:
parties_new = pd.read_csv('data/new/parties.csv', dtype=dtype)
print(parties_new.party_drug_physical.unique())
print(parties_new.cellphone_use.unique())
print(parties_new.party_sex.unique())
print(parties.school_bus_related.unique())
print(parties.at_fault.unique())
print(parties.hazardous_materials.unique())

[nan 'H' 'E' 'I' 'F']
['C' 'D' nan 'B']
['F' nan 'M']
[0 1]
[1 0]
[0 1]


# Checking unique values

In [32]:
pcfs = pd.read_csv('data/new/pcf.csv', dtype=dtype)
print(pcfs.columns)
#pcfs.violation_category.unique()

Index(['pcf_id', 'pcf_violation', 'pcf_violation_category',
       'pcf_violation_subsection', 'primary_collision_factor'],
      dtype='object')


In [33]:
pcfs.pcf_violation_category.unique()

array(['improper turning', 'hazardous parking',
       'other hazardous violation', 'traffic signals and signs',
       'speeding', 'unsafe starting or backing', 'unsafe lane change',
       'automobile right of way', 'wrong side of road', 'dui',
       'other than driver (or pedestrian)', 'fell asleep',
       'improper passing', 'pedestrian right of way', 'unknown',
       'following too closely', nan, 'other improper driving',
       'pedestrian violation', 'other equipment', 'impeding traffic',
       'brakes', 'lights', 'pedestrian dui', '21804'], dtype=object)

In [28]:
# TODO: drop duplicated in parties?